export const CHANGE_THEME = "CHANGE-THEME"

export const TOGGLE_DRAWER = "TOGGLE-DRAWER"

export const CREATE_FILE = "CREATE-FILE"

export const DELETE_FILE = 'DELETE-FILE'

export const UPDATE_FILE = 'UPDATE-FILE'

export const ADD_FILE_TO_FOLDER = 'ADD-FILE-TO-FOLDER'

export const CREATE_FOLDER = 'CREATE-FOLDER'

export const DELETE_FOLDER = 'DELETE-FOLDER'
